services:
  core:
    container_name: core
    build: 
      context: .
    ports:
      - 5000:5000
    volumes:
      - amplec_persistence:/home/core/persistence
    networks:
      - amplec

networks:
  amplec:
    name: amplec
volumes:
  amplec_persistence:
    name: amplec_persistence